version: 2
updates:
  - package-ecosystem: npm
    directory: "/adapters/playwright"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      playwright-adapter-dependencies:
        patterns:
          - "*"

  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      rust-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
